# Generated by Django 2.0.3 on 2018-07-01 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.CharField(max_length=8192),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=4096),
        ),
    ]
