# Generated by Django 2.0.3 on 2018-07-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_auto_20180702_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='question',
        ),
    ]
